### ISSUE TITLE
authorize called too soon

### ISSUE THREAD

**Issue by kenjindomini** [kenjindomini/gmail-notification-chrome-extension#9]
authorized is calling gapi before client.js is loaded:
Error in response to identity.getAuthToken: ReferenceError: gapi is not defined
    at loadApi (chrome-extension://kpokojddapokpbpongpihjjpmppmmgln/eventPage.js:67:5)
    at Object.callback (chrome-extension://kpokojddapokpbpongpihjjpmppmmgln/eventPage.js:46:11)
    at authenticate (chrome-extension://kpokojddapokpbpongpihjjpmppmmgln/eventPage.js:40:18)
    at messageHandler (chrome-extension://kpokojddapokpbpongpihjjpmppmmgln/eventPage.js:160:13)

**Comment by kenjindomini** [comment]
script src now includes an onload and authorize and sync have been offloaded to a new function, init()
